apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: default-esp-backend
  name: default-esp-backend
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-esp-backend
  template:
    metadata:
      labels:
        app: default-esp-backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.3
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always