apiVersion: v1
kind: Pod
metadata:
  name: {{ .ServiceName }}-esp
  namespace: {{ .Namespace }}
  labels:
    app: {{ .ServiceName }}-esp
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: esp
    image: {{ .ContainerImage }}
    args: [
      "-p", "8080",
      "-a", "{{ .Upstream }}",
      "-s", "{{ .Endpoint }}",
      "-v", "{{ .ConfigVersion }}",
      "-z", "healthz",
    ]
    readinessProbe:
      httpGet:
        host: "{{ .Host }}"
        path: /_gcp_iap/identity
        port: 443
        scheme: HTTPS
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 2
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    ports:
      - containerPort: 8080