apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .ServiceName }}-esp
  namespace: {{ .Namespace }}
  labels:
    app: {{ .ServiceName }}-esp
data:
  ENDPOINT: {{ .Endpoint }}
  CONFIG_VERSION: {{ .ConfigVersion }}
  HOST: {{ .Host }}