swagger: "2.0"
info:
  description: "wildcard config for any HTTP service behind IAP. SIG={{ .Signature }}"
  title: "General HTTP Service using IAP"
  version: "1.0.0"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"
paths:
  "/**":
    get:
      operationId: Get
      responses:
        '200':
          description: Get
        default:
          description: Error
    delete:
      operationId: Delete
      responses:
        '204':
          description: Delete
        default:
          description: Error
    patch:
      operationId: Patch
      responses:
        '200':
          description: Patch
        default:
          description: Error
    post:
      operationId: Post
      responses:
        '200':
          description: Post
        default:
          description: Error
    put:
      operationId: Put
      responses:
        '200':
          description: Put
        default:
          description: Error

securityDefinitions:
  google_jwt:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # This must match the 'iss' field in the JWT.
    x-google-issuer: "https://cloud.google.com/iap"
    # Update this with your service account's email address.
    x-google-jwks_uri: "https://www.gstatic.com/iap/verify/public_key-jwk"
    # This must match the "aud" field in the JWT. You can add multiple audiences to accept JWTs from multiple clients.
    x-google-audiences: "{{ .JWTAudience }}"

host: "{{ .Endpoint }}"
x-google-endpoints:
- name: "{{ .Endpoint }}"
  target: "{{ .Address }}"