apiVersion: v1
kind: ConfigMap
metadata:
  name: iapingress-controller
  namespace: metacontroller
  labels:
    app: {{ template "iapingress-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: iapingress-controller
data:
  esp-replicaset.yaml: |
{{ .Files.Get "config/esp-replicaset.yaml" | indent 4 }}
  default-esp-backend.yaml: |
{{ .Files.Get "config/default-esp-backend.yaml" | indent 4 }}
  default-esp-backend-svc.yaml: |
{{ .Files.Get "config/default-esp-backend-svc.yaml" | indent 4 }}
  openapi.yaml: |
{{ .Files.Get "config/openapi.yaml" | indent 4 }}
  nginx-auto.conf.template: |
{{ .Files.Get "config/nginx-auto.conf.template" | indent 4 }}