apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iapingresses.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  version: v1
  scope: Namespaced
  names:
    plural: iapingresses
    singular: iapingress
    kind: IapIngress
    shortNames: ["iaping", "iapig"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: LambdaController
metadata:
  name: iapingress-controller
spec:
  parentResource:
    apiVersion: ctl.isla.solutions/v1
    resource: iapingresses
  childResources:
    - apiVersion: v1
      resources: ["services", "pods"]
    - apiVersion: extensions/v1beta1
      resources: ["ingresses"]
  clientConfig:
    service:
      name: iapingress-controller
      namespace: metacontroller
    caBundle: ...
  hooks:
    sync:
      path: /sync
  generateSelector: true