apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "iapingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "iapingress-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "iapingress-controller.fullname" . }}
  labels:
    app: {{ template "iapingress-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "iapingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "iapingress-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "iapingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "iapingress-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["extensions", "replicasets"]
  resources: ["ingresses"]
  verbs: ["get", "list", "update", "patch"]