apiVersion: v1
kind: Service
metadata:
  name: {{ template "iapingress-controller.fullname" . }}
  labels:
    app: {{ template "iapingress-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: iapingress-controller
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: {{ template "iapingress-controller.name" . }}
    release: {{ .Release.Name }}
  