# Default values for iapingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

cloudSA:
  enabled: false
  secretName:
  secretKey:

godev:
  enabled: false
  persistence:
    enabled: true
    size: 10Gi
    nfsHost: godev-nfs-nfs-server.metacontroller.svc.cluster.local
    nfsPath: /exports

image:
  repository: gcr.io/cloud-solutions-group/iapingress-controller
  tag: 0.1.8
  pullPolicy: IfNotPresent